/**
 * Represents a designated landing and storage zone for jetpack aircraft.
 * 
 * Purpose:
 * Models a physical parking location within a city where jetpacks can safely land, be stored, and
 * launch from. Tracks occupancy status to support resource allocation and prevent double-booking.
 * Provides spatial coordinates for rendering parking zones on maps and calculating proximity during
 * landing operations.
 * 
 * Key Responsibilities:
 * - Maintain unique identifier for parking space registry and reference
 * - Store immutable geographic coordinates (x, y) for precise location
 * - Track occupancy state (occupied/vacant) for availability checks
 * - Provide occupy() and vacate() operations for state transitions
 * - Support string representation for logging and display
 * 
 * Interactions:
 * - Managed by ParkingSpaceManager for allocation and availability queries
 * - Generated by ParkingSpaceGenerator for procedural city infrastructure
 * - Displayed on CityMapPanel and MapDisplayPanel as visual markers
 * - Referenced in City model as part of urban infrastructure
 * - Used in flight landing logic to determine valid destination zones
 * 
 * Patterns & Constraints:
 * - Immutable location ensures spatial integrity; position cannot change after creation
 * - Mutable occupancy state supports real-time allocation updates
 * - Lightweight value object suitable for large-scale parking networks
 * - Thread-safe reads; synchronized writes required for occupancy at higher layers
 * 
 * @author Haisam Elkewidy
 */

package com.example.model;

/**
 * Parking space model for jetpack landing zones.
 * Tracks location and occupancy status for resource allocation.
 */
public class ParkingSpace {
    // Unique identifier for this parking space
    private final String id;
    // X-coordinate of parking space location
    private final double x;
    // Y-coordinate of parking space location
    private final double y;
    // Flag indicating if space is currently occupied
    private boolean occupied;

    /**
     * Constructs a new ParkingSpace with double coordinates.
     * Space is vacant by default.
     *
     * @param id Unique parking space identifier
     * @param x X-coordinate position
     * @param y Y-coordinate position
     */
    public ParkingSpace(String id, double x, double y) {
        // Set immutable parking space ID
        this.id = id;
        // Set immutable X position
        this.x = x;
        // Set immutable Y position
        this.y = y;
        // Initialize as vacant (not occupied)
        this.occupied = false;
    }

    /**
     * Constructs a new ParkingSpace with integer coordinates.
     * Converts int coordinates to double and delegates to primary constructor.
     *
     * @param id Unique parking space identifier
     * @param x X-coordinate position (integer)
     * @param y Y-coordinate position (integer)
     */
    public ParkingSpace(String id, int x, int y) {
        // Convert int coordinates to double and call primary constructor
        this(id, (double)x, (double)y);
    }

    /**
     * Gets the parking space identifier.
     *
     * @return Parking space ID
     */
    public String getId() {
        return id;
    }

    /**
     * Gets the X-coordinate of parking space.
     *
     * @return X position
     */
    public double getX() {
        return x;
    }

    /**
     * Gets the Y-coordinate of parking space.
     *
     * @return Y position
     */
    public double getY() {
        return y;
    }

    /**
     * Checks if parking space is currently occupied.
     *
     * @return true if occupied, false if vacant
     */
    public boolean isOccupied() {
        return occupied;
    }

    /**
     * Marks parking space as occupied.
     * Updates occupancy flag to indicate space is in use.
     */
    public void occupy() {
        // Set occupied flag to true
        this.occupied = true;
    }

    /**
     * Marks parking space as vacant.
     * Updates occupancy flag to indicate space is available.
     */
    public void vacate() {
        // Set occupied flag to false
        this.occupied = false;
    }

    /**
     * Returns formatted string representation of parking space.
     *
     * @return String with ID, coordinates, and occupancy status
     */
    @Override
    public String toString() {
        // Format as: ParkingSpace[id=X, x=Y, y=Z, occupied=boolean]
        return String.format("ParkingSpace[id=%s, x=%.3f, y=%.3f, occupied=%s]", id, x, y, occupied);
    }
}
