/**
 * Represents a designated landing and storage zone for jetpack aircraft.
 * 
 * Purpose:
 * Models a physical parking location within a city where jetpacks can safely land, be stored, and
 * launch from. Tracks occupancy status to support resource allocation and prevent double-booking.
 * Provides spatial coordinates for rendering parking zones on maps and calculating proximity during
 * landing operations.
 * 
 * Key Responsibilities:
 * - Maintain unique identifier for parking space registry and reference
 * - Store immutable geographic coordinates (x, y) for precise location
 * - Track occupancy state (occupied/vacant) for availability checks
 * - Provide occupy() and vacate() operations for state transitions
 * - Support string representation for logging and display
 * 
 * Interactions:
 * - Managed by ParkingSpaceManager for allocation and availability queries
 * - Generated by ParkingSpaceGenerator for procedural city infrastructure
 * - Displayed on CityMapPanel and MapDisplayPanel as visual markers
 * - Referenced in City model as part of urban infrastructure
 * - Used in flight landing logic to determine valid destination zones
 * 
 * Patterns & Constraints:
 * - Immutable location ensures spatial integrity; position cannot change after creation
 * - Mutable occupancy state supports real-time allocation updates
 * - Lightweight value object suitable for large-scale parking networks
 * - Thread-safe reads; synchronized writes required for occupancy at higher layers
 * 
 * @author Haisam Elkewidy
 */

package com.example.model;

public class ParkingSpace {
    /** Unique identifier for this parking space (e.g., "NYC-P001") */
    private final String id;
    /** The x-coordinate location of this parking space */
    private final double x;
    /** The y-coordinate location of this parking space */
    private final double y;
    /** Whether this parking space is currently occupied by a jetpack */
    private boolean occupied;

    /**
     * Constructs a new ParkingSpace at the specified coordinates.
     * Space is initially vacant (not occupied).
     * 
     * @param id unique identifier for this parking space
     * @param x the x-coordinate location
     * @param y the y-coordinate location
     */
    public ParkingSpace(String id, double x, double y) {
        this.id = id;             // Store the parking space ID
        this.x = x;               // Store the x-coordinate
        this.y = y;               // Store the y-coordinate
        this.occupied = false;    // Initialize as vacant
    }

    /**
     * Constructs a new ParkingSpace with integer coordinates.
     * Delegates to the double-precision constructor.
     * 
     * @param id unique identifier for this parking space
     * @param x the x-coordinate location (integer)
     * @param y the y-coordinate location (integer)
     */
    public ParkingSpace(String id, int x, int y) {
        this(id, (double)x, (double)y);  // Convert to double and call primary constructor
    }

    /**
     * Returns the unique identifier of this parking space.
     * @return the parking space ID string
     */
    public String getId() {
        return id;  // Return the stored ID
    }

    /**
     * Returns the x-coordinate of this parking space.
     * @return the x-coordinate value
     */
    public double getX() {
        return x;  // Return the stored x-coordinate
    }

    /**
     * Returns the y-coordinate of this parking space.
     * @return the y-coordinate value
     */
    public double getY() {
        return y;  // Return the stored y-coordinate
    }

    /**
     * Checks if this parking space is currently occupied.
     * @return true if occupied, false if vacant
     */
    public boolean isOccupied() {
        return occupied;  // Return the occupation status
    }

    /**
     * Marks this parking space as occupied.
     * Called when a jetpack parks here.
     */
    public void occupy() {
        this.occupied = true;  // Set occupied flag to true
    }

    /**
     * Marks this parking space as vacant.
     * Called when a jetpack leaves this space.
     */
    public void vacate() {
        this.occupied = false;  // Set occupied flag to false
    }

    /**
     * Returns a string representation of this parking space.
     * @return formatted string with ID, coordinates, and occupation status
     */
    @Override
    public String toString() {
        return String.format("ParkingSpace[id=%s, x=%.3f, y=%.3f, occupied=%s]", id, x, y, occupied);  // Format and return parking space info
    }
}
