#!/usr/bin/env bash
# ==============================================================================
# wipe_and_merge_markdown.sh - Consolidate documentation into README.md
# ==============================================================================
# Purpose:
#   Merges all Markdown files in the repository into a single README.md,
#   providing consolidated documentation. Optionally deletes source Markdown
#   files after merge to eliminate duplication. Useful for creating unified
#   documentation artifacts or preparing for documentation refactoring.
#
# Usage:
#   ./tools/wipe_and_merge_markdown.sh        -> Merge into README.md (preserve sources)
#   ./tools/wipe_and_merge_markdown.sh -y     -> Merge and delete source .md files
#
# Features:
#   - Recursively finds all .md files in repository
#   - Preserves source file paths in merged output for traceability
#   - Excludes README.md itself from merge to avoid circularity
#   - Optional deletion mode with confirmation flag (-y)
#   - POSIX-compatible shell script for cross-platform execution
#
# Requirements:
#   - Bash shell (v4.0+)
#   - find, sort, cat utilities
#   - Write permissions in repository root
#
# Author: Haisam Elkewidy
# ==============================================================================

set -euo pipefail

# Wipes README.md and appends plain text from all other .md files in the repo.
# Usage:
#   ./tools/wipe_and_merge_markdown.sh        -> Overwrites README.md with merged content
#   ./tools/wipe_and_merge_markdown.sh -y     -> Also deletes source .md files (excluding README.md)

CONFIRM_DELETE="${1:-}"

# Ensure README.md exists
if [[ ! -f "README.md" ]]; then
  echo "[INFO] README.md not found. Creating an empty README.md..."
  touch README.md
fi

ROOT_README_ABS="$(cd "$(dirname "README.md")" && pwd)/$(basename "README.md")"

# 1) Wipe README.md clean and seed header
cat > README.md <<'HDR'
# Consolidated Documentation

This README was auto-generated by wipe_and_merge_markdown.sh.
It contains the plain text from all other Markdown files in this repository.

HDR

# 2) Collect all markdown files recursively, sorted by path
mapfile -t FILES < <(find . -type f -name "*.md" 2>/dev/null | LC_ALL=C sort)

# Check if any markdown files were found
if [[ ${#FILES[@]} -eq 0 ]]; then
  echo "[WARNING] No markdown files found in repository."
  exit 0
fi

# 3) Append each file content except the root README.md
for F in "${FILES[@]}"; do
  F_ABS="$(cd "$(dirname "$F")" && pwd)/$(basename "$F")"
  if [[ "$F_ABS" != "$ROOT_README_ABS" ]]; then
    {
      echo ""
      echo "---"
      echo "From: $F"
      echo "---"
      echo ""
    } >> README.md
    cat "$F" >> README.md
    echo "" >> README.md
  fi
done

echo "[OK] README.md has been wiped and rebuilt from all other Markdown files."

# 4) Optional deletion
if [[ "${CONFIRM_DELETE}" == "-y" ]]; then
  echo "[INFO] Deleting source Markdown files (excluding README.md)..."
  for F in "${FILES[@]}"; do
    F_ABS="$(cd "$(dirname "$F")" && pwd)/$(basename "$F")"
    if [[ "$F_ABS" != "$ROOT_README_ABS" ]]; then
      rm -f -- "$F"
    fi
  done
  echo "[OK] Source Markdown files deleted."
else
  echo "[INFO] Skipping deletion. Run with -y to remove source Markdown files."
fi
