@echo off
setlocal enabledelayedexpansion

REM Wipes README.md and appends plain text from all other .md files in the repo.
REM Usage:
REM   wipe_and_merge_markdown.bat           -> Overwrites README.md with merged content
REM   wipe_and_merge_markdown.bat -y        -> Also deletes source .md files (excluding README.md)

set "CONFIRM_DELETE=%~1"

REM Ensure we're at repo root with README.md present (create if missing)
if not exist "README.md" (
  echo [INFO] README.md not found. Creating an empty README.md...
  type nul > "README.md"
  if errorlevel 1 (
    echo [ERROR] Failed to create README.md
    exit /b 1
  )
)

set "ROOT_README=%CD%\README.md"

REM 1) Wipe README.md clean
> "README.md" (
  echo # Consolidated Documentation
  echo.
  echo This README was auto-generated by wipe_and_merge_markdown.bat.
  echo It contains the plain text from all other Markdown files in this repository.
  echo.
)

REM 2) Find all *.md files recursively, sorted by path, excluding the root README.md
for /f "delims=" %%F in ('powershell -NoProfile -Command ^
  "Get-ChildItem -LiteralPath . -Filter *.md -Recurse | Sort-Object FullName | ForEach-Object { $_.FullName }"') do (
  set "FILE=%%~fF"
  if /I not "!FILE!"=="%ROOT_README%" (
    REM 3) Append a simple header and the plain text content
    >> "README.md" (
      echo ---
      echo From: !FILE:%CD%\=.! 
      echo ---
      echo.
    )
    type "%%~fF" >> "README.md"
    echo.>> "README.md"
  )
)

echo [OK] README.md has been wiped and rebuilt from all other Markdown files.

REM 4) Optional deletion of source Markdown files (excluding README.md)
if /I "%CONFIRM_DELETE%"=="-y" (
  echo [INFO] Deleting source Markdown files (excluding README.md)...
  for /f "delims=" %%F in ('powershell -NoProfile -Command ^
    "Get-ChildItem -LiteralPath . -Filter *.md -Recurse | Sort-Object FullName | ForEach-Object { $_.FullName }"') do (
    set "FILE=%%~fF"
    if /I not "!FILE!"=="%ROOT_README%" (
      del /f /q "%%~fF"
    )
  )
  echo [OK] Source Markdown files deleted.
) else (
  echo [INFO] Skipping deletion. Run with -y to remove source Markdown files.
)

endlocal
