@echo off
setlocal enabledelayedexpansion

REM Wipes README.md and appends plain text from all other .md files in the repo.
REM Adds structured header, Table of Contents, and JOGL instructions.
REM Usage:
REM   wipe_and_merge_markdown.bat           -> Overwrites README.md with merged content
REM   wipe_and_merge_markdown.bat -y        -> Also deletes source .md files (excluding README.md)

set "CONFIRM_DELETE=%~1"

if not exist "README.md" (
  echo [INFO] README.md not found. Creating an empty README.md...
  type nul > "README.md"
)

set "ROOT_README=%CD%\README.md"

> "README.md" (
  echo # Jetpack Air Traffic Controller — Consolidated Documentation
  echo
  echo A single README consolidating all project documentation and guides.
  echo
  echo ## Table of Contents
  echo - [Overview](#overview)
  echo - [Architecture](#architecture)
  echo - [Features](#features)
  echo - [3D and JOGL Graphics](#3d-and-jogl-graphics)
  echo - [Tracking and City Logs](#tracking-and-city-logs)
  echo - [Build and Run (JOGL)](#build-and-run-jogl)
  echo - [Testing](#testing)
  echo - [Refactoring and Codebase Evolution](#refactoring-and-codebase-evolution)
  echo - [Utilities, Scripts, and Tools](#utilities-scripts-and-tools)
  echo - [Data, Resources, and Reports](#data-resources-and-reports)
  echo - [Troubleshooting](#troubleshooting)
  echo - [Documentation Index](#documentation-index)
  echo
  echo ## Overview
  echo This README was auto-generated by wipe_and_merge_markdown.bat and includes the full text of all other Markdown files in this repository.
  echo
  echo ## Build and Run (JOGL)
  echo These steps use the provided Windows batch scripts to build and run the JOGL-enabled visualization:
  echo
  echo 1. Ensure Java and Maven are installed and configured. On Windows, use setup-maven.bat if provided.
  echo 2. Build with JOGL:
  echo
  echo    ^`^`^`
  echo    build_with_jogl.bat
  echo    ^`^`^`
  echo
  echo 3. Run with JOGL:
  echo
  echo    ^`^`^`
  echo    run_with_jogl.bat
  echo    ^`^`^`
  echo
  echo For non-Windows or cross-platform builds, use Maven directly and refer to JOGL documentation sections included below.
  echo
  echo ---
  echo Consolidated documentation from all Markdown files in the repository (excluding this root README.md):
  echo ---
  echo
)

for /f "delims=" %%F in ('powershell -NoProfile -Command ^
  "Get-ChildItem -LiteralPath . -Filter *.md -Recurse | Sort-Object FullName | ForEach-Object { $_.FullName }"') do (
  set "FILE=%%~fF"
  if /I not "!FILE!"=="%ROOT_README%" (
    >> "README.md" (
      echo
      echo ---
      echo ## From !FILE:%CD%\=.! 
      echo ---
      echo
    )
    type "%%~fF" >> "README.md"
    echo.>> "README.md"
  )
)

echo [OK] README.md has been wiped and rebuilt from all other Markdown files.

if /I "%CONFIRM_DELETE%"=="-y" (
  echo [INFO] Deleting source Markdown files (excluding README.md)...
  for /f "delims=" %%F in ('powershell -NoProfile -Command ^
    "Get-ChildItem -LiteralPath . -Filter *.md -Recurse | Sort-Object FullName | ForEach-Object { $_.FullName }"') do (
    set "FILE=%%~fF"
    if /I not "!FILE!"=="%ROOT_README%" (
      del /f /q "%%~fF"
    )
  )
  echo [OK] Source Markdown files deleted.
) else (
  echo [INFO] Skipping deletion. Run with -y to remove source Markdown files.
)

endlocal
