#!/usr/bin/env bash
set -euo pipefail

CONFIRM_DELETE="${1:-}"

if [[ ! -f "README.md" ]]; then
  echo "[INFO] README.md not found. Creating an empty README.md..."
  : > README.md
fi

ROOT_README_ABS="$(python -c 'import os; print(os.path.abspath("README.md"))')"

cat > README.md <<'HDR'
# Jetpack Air Traffic Controller — Consolidated Documentation

A single README consolidating all project documentation and guides.

## Table of Contents
- [Overview](#overview)
- [Architecture](#architecture)
- [Features](#features)
- [3D and JOGL Graphics](#3d-and-jogl-graphics)
- [Tracking and City Logs](#tracking-and-city-logs)
- [Build and Run (JOGL)](#build-and-run-jogl)
- [Testing](#testing)
- [Refactoring and Codebase Evolution](#refactoring-and-codebase-evolution)
- [Utilities, Scripts, and Tools](#utilities-scripts-and-tools)
- [Data, Resources, and Reports](#data-resources-and-reports)
- [Troubleshooting](#troubleshooting)
- [Documentation Index](#documentation-index)

## Overview
This README was auto-generated by wipe_and_merge_markdown.sh and includes the full text of all other Markdown files in this repository.

## Build and Run (JOGL)
These steps use the provided Windows batch scripts to build and run the JOGL-enabled visualization:

1. Ensure Java and Maven are installed and configured. On Windows, use setup-maven.bat if provided.
2. Build with JOGL:
```
build_with_jogl.bat
```
3. Run with JOGL:
```
run_with_jogl.bat
```

For non-Windows or cross-platform builds, use Maven directly and refer to JOGL documentation sections included below.

---
Consolidated documentation from all Markdown files in the repository (excluding this root README.md):
---

HDR

mapfile -t FILES < <(find . -type f -name "*.md" -print0 | xargs -0 -I{} python - <<'PY'
import os, sys
print(os.path.abspath(sys.argv[1]))
PY {} | LC_ALL=C sort)

for F in "${FILES[@]}"; do
  if [[ "$F" != "$ROOT_README_ABS" ]]; then
    REL="$(python - <<'PY'
import os,sys
root=os.path.abspath(".")
path=sys.stdin.read().strip()
print(os.path.relpath(path, root))
PY <<<"$F")"
    {
      echo ""
      echo "---"
      echo "## From ./$REL"
      echo "---"
      echo ""
    } >> README.md
    cat "$F" >> README.md
    echo "" >> README.md
  fi
done

echo "[OK] README.md has been wiped and rebuilt from all other Markdown files."

if [[ "${CONFIRM_DELETE}" == "-y" ]]; then
  echo "[INFO] Deleting source Markdown files (excluding README.md)..."
  for F in "${FILES[@]}"; do
    if [[ "$F" != "$ROOT_README_ABS" ]]; then
      rm -f -- "$F"
    fi
  done
  echo "[OK] Source Markdown files deleted."
else
  echo "[INFO] Skipping deletion. Run with -y to remove source Markdown files."
fi
